---@type LazySpec
return {
  "AstroNvim/astroui",
  priority = 1000,
  ---@type AstroUIOpts
  opts = {
    -- change colorscheme
    colorscheme = "onedark",
    -- AstroUI allows you to easily modify highlight groups easily for any and all colorschemes
    highlights = {
      init = { -- this table overrides highlights in all themes
        -- Normal = { bg = "#000000" },
      },
      astrotheme = { -- a table of overrides/changes when applying the astrotheme theme
        -- Normal = { bg = "#000000" },
      },
    },
    -- Icons can be configured throughout the interface
    icons = {
      -- configure the loading of the lsp in the status line
      LSPLoading1 = "⠋",
      LSPLoading2 = "⠙",
      LSPLoading3 = "⠹",
      LSPLoading4 = "⠸",
      LSPLoading5 = "⠼",
      LSPLoading6 = "⠴",
      LSPLoading7 = "⠦",
      LSPLoading8 = "⠧",
      LSPLoading9 = "⠇",
      LSPLoading10 = "⠏",
      ActiveLSP = "",
      ActiveTS = "",
      BufferClose = "",
      DapBreakpoint = "",
      DapBreakpointCondition = "",
      DapBreakpointRejected = "",
      Diagnostic = "",
      DapLogPoint = "",
      DapStopped = "",
      DefaultFile = "",
      DiagnosticError = "",
      DiagnosticHint = "",
      DiagnosticInfo = "",
      DiagnosticWarn = "",
      Ellipsis = "",
      FileModified = "",
      FileReadOnly = "",
      FoldClosed = "",
      FoldOpened = "",
      FolderClosed = "󰉋",
      FolderEmpty = "󰉖",
      FolderOpen = "",
      GitAdd = "",
      GitBranch = "",
      GitChange = "",
      GitConflict = "",
      GitDelete = "",
      GitIgnored = "",
      GitRenamed = "",
      GitStaged = "",
      GitUnstaged = "",
      GitUntracked = "",
      LSPLoaded = "",
      MacroRecording = "",
      Paste = "",
      Search = "",
      Selected = "",
      TabClose = "",
      DB = "",
      Version = "󰏕",
      Ai = "󱚣",

      Array = "",
      Boolean = "",
      Class = "",
      Color = "",
      Constant = "",
      Enum = "",
      EnumMember = "",
      Event = "",
      Field = "",
      File = "",
      Interface = "",
      Key = "",
      Keyword = "",
      Method = "",
      Misc = "",
      Namespace = "",
      Numeric = "",
      Operator = "",
      Parameter = "",
      Package = "",
      Property = "",
      Ruler = "",
      Snippet = "",
      String = "",
      Structure = "",
      Variable = "",
    },
    status = {
      separators = {
        none = { "", "" },
        left = { "", "  " },
        right = { "  ", "" },
        center = { "  ", "  " },
        tab = { " ", " " },
        breadcrumbs = "  ",
        path = "  ",
      },
      colors = {
        buffer_active_fg = "#98c379",
      },
      attributes = {
        buffer_active = { bold = true, italic = false },
      },
    },
  },
}
