theme = "gruvbox_mix_dark"

[editor]
line-number = "relative"
mouse = false
bufferline = "always"
completion-replace = true
completion-trigger-len = 1
true-color = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "info"

[editor.statusline]
left = [
  "mode",
  "version-control",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
]
center = []
right = [
  "spinner",
  "diagnostics",
  "selections",
  "register",
  "position",
  "file-encoding",
]

[editor.indent-guides]
character = "│"
render = true

[editor.lsp]
display-inlay-hints = true
display-messages = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection", ":w"]
"C-u" = ["half_page_up", "align_view_center"]
"C-d" = ["half_page_down", "align_view_center"]
"y" = [
  "yank_main_selection_to_clipboard",
  "normal_mode",
  "flip_selections",
  "collapse_selection",
]
"Y" = [
  "extend_to_line_bounds",
  "yank_main_selection_to_clipboard",
  "goto_line_start",
  "collapse_selection",
]
"p" = "paste_clipboard_after"
"P" = "paste_clipboard_before"
"C-h" = "jump_view_left"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"
"C-l" = "jump_view_right"
"K" = "insert_newline"
# Move line up/down using A-k, A-j
"A-k" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
"A-j" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_down",
  "paste_before",
]

[keys.normal.g]
q = ":bc"
Q = ":bc!"

[keys.normal."]"]
b = ":bn"

[keys.normal."["]
b = ":bp"

[keys.normal.space]
c = ":buffer-close"

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
# VSCode-like auto-completeion (pretty much all IDEs do it on C-space)
"C-space" = "completion"

# Config Mode
[keys.normal."A-c"]
r = [":config-reload", ":reload-all"]
o = ":config-open"
l = ":o ~/.config/helix/languages.toml"

[keys.select]
# Visual-mode specific muscle memory
i = "select_textobject_inner"
a = "select_textobject_around"

# Some extra binds to allow us to insert/append in select mode because it's nice with multiple cursors
tab = [
  "insert_mode",
  "collapse_selection",
] # tab is read by most terminal editors as "C-i"
C-a = ["append_mode", "collapse_selection"]

# Make selecting lines in visual mode behave sensibly
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]

# Clipboards over registers ye ye
d = ["yank_main_selection_to_clipboard", "delete_selection"]
x = ["yank_main_selection_to_clipboard", "delete_selection"]
y = [
  "yank_main_selection_to_clipboard",
  "normal_mode",
  "flip_selections",
  "collapse_selection",
]
Y = [
  "extend_to_line_bounds",
  "yank_main_selection_to_clipboard",
  "goto_line_start",
  "collapse_selection",
  "normal_mode",
]
p = "replace_selections_with_clipboard" # No life without this
P = "paste_clipboard_before"

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
