frame = "none"
maximized = true

[font]
normal = [
    { family = "JetBrainsMono NFP" },
    "Symbols Nerd Font",
    "Noto Color Emoji",
]

edging = "antialias"
hinting = "full"
allow_float_size = true
size = 12


[font.features]
"JetBrainsMono NFP" = ["+zero", "+cv06", "+cv07", "+ss19"]

[box-drawing]
type = "native"
thickness-multipliers = [0.25, 0.5, 0.75]
stroke-width-ratio = 0.15
