frame = "none"
maximized = true

[font]
normal = [
    { family = "Typekasf Nerd Font Propo" },
    "Symbols Nerd Font",
    "Noto Color Emoji",
]

edging = "antialias"
hinting = "full"
allow_float_size = true
size = 12

[font.features]
"JetBrainsMono NFP" = ["+zero", "+cv06", "+cv07", "+ss19", "-calt"]
"0xProto Nerd Font Propo" = ["+ss01"]

[box-drawing]
mode = "native"

[box-drawing.sizes]
default = [1, 2]  # Thin and thick values respectively, below 12px
