frame = "none"
maximized = true

[font]
normal = [
    { family = "Iosevkasf" },
    { family = "JetBrains Mono" },
    { family = "Intel One Mono", style = "Regular" },
    "Symbols Nerd Font",
    "Noto Color Emoji",
]

edging = "antialias"
hinting = "full"
allow_float_size = true
size = 12

[font.features]
"JetBrains Mono" = ["+zero", "+cv06", "+cv07", "+ss19", "+ss16"]
