# Author: Hadey Lucas <lhflyextra300@gmail.com>
# Upstream: https://github.com/ARTSYS-H/lugh
# Contributing:
#   Please submit changes to https://github.com/ARTSYS-H/lugh

inherits = "lugh"

[palette]
base = "#020202"
surface = "#0D0D0D"
overlay = "#282830"
