require("plugins.treesitter")
require("plugins.galaxyline")
require("plugins.telescope")
require("plugins.nvimtree")
require("plugins.floaterm")
require("plugins.gitsigns")
require("plugins.hop")
require("plugins.hexokinase")
